definitions:
  handler.CreateOpeningRequest:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    required:
    - company
    - link
    - location
    - remote
    - role
    - salary
    type: object
  handler.CreateOpeningResponse:
    properties:
      message:
        type: string
      opening:
        $ref: '#/definitions/schemas.OpeningResponse'
    type: object
  handler.DeleteOpeningResponse:
    properties:
      message:
        type: string
      opening:
        $ref: '#/definitions/schemas.OpeningResponse'
    type: object
  handler.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  handler.ListOpeningResponse:
    properties:
      openings:
        items:
          $ref: '#/definitions/schemas.OpeningResponse'
        type: array
    type: object
  handler.ShowOpeningResponse:
    properties:
      opening:
        $ref: '#/definitions/schemas.OpeningResponse'
    type: object
  handler.UpdateOpeningRequest:
    properties:
      company:
        type: string
      id:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    required:
    - company
    - id
    - link
    - location
    - remote
    - role
    - salary
    type: object
  handler.UpdateOpeningResponse:
    properties:
      message:
        type: string
      opening:
        $ref: '#/definitions/schemas.OpeningResponse'
    type: object
  schemas.OpeningResponse:
    properties:
      company:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /opening:
    delete:
      consumes:
      - application/json
      description: Delete a job opening
      parameters:
      - description: Opening ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteOpeningResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Delete a job opening
      tags:
      - opening
    get:
      consumes:
      - application/json
      description: Show a job opening
      parameters:
      - description: Opening ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowOpeningResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Show a job opening
      tags:
      - opening
    post:
      consumes:
      - application/json
      description: Create a new job opening
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateOpeningRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateOpeningResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create a new job opening
      tags:
      - opening
    put:
      consumes:
      - application/json
      description: Update a job opening
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateOpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateOpeningResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Update a job opening
      tags:
      - opening
  /openings:
    get:
      consumes:
      - application/json
      description: List job openings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListOpeningResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: List job openings
      tags:
      - openings
swagger: "2.0"
